import uuid
from datetime import datetime

from sqlalchemy import (
    Column, String, Integer, Float,
    Text, DateTime, ForeignKey,
)
from sqlalchemy.orm import relationship

from app.storage.db import Base


def _uuid() -> str:
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Document — one row per uploaded PDF
# ---------------------------------------------------------------------------

class Document(Base):
    __tablename__ = "documents"

    doc_id      = Column(String, primary_key=True, default=_uuid)
    project_id  = Column(String, nullable=False, index=True)
    filename    = Column(String, nullable=False)
    title       = Column(String)
    page_count  = Column(Integer, default=0)
    file_path   = Column(String)

    # queued | processing | indexed | failed
    status      = Column(String, default="queued")
    upload_date = Column(DateTime, default=datetime.utcnow)

    chunks = relationship(
        "Chunk", back_populates="document", cascade="all, delete-orphan"
    )
    source_guide = relationship(
        "SourceGuide", back_populates="document",
        cascade="all, delete-orphan", uselist=False
    )


# ---------------------------------------------------------------------------
# Chunk — one row per text chunk extracted from a PDF
# ---------------------------------------------------------------------------

class Chunk(Base):
    __tablename__ = "chunks"

    chunk_id    = Column(String, primary_key=True, default=_uuid)
    doc_id      = Column(String, ForeignKey("documents.doc_id"), nullable=False, index=True)
    project_id  = Column(String, nullable=False, index=True)
    page_number = Column(Integer, nullable=False)

    # 1=doc summary  2=section  3=paragraph  4=sentence
    level       = Column(Integer, nullable=False)
    section     = Column(String, default="main")
    text        = Column(Text, nullable=False)
    word_count  = Column(Integer, default=0)

    # Position of this chunk inside its project's FAISS index
    # Needed to map FAISS search results back to chunk text
    faiss_idx   = Column(Integer)

    document = relationship("Document", back_populates="chunks")


# ---------------------------------------------------------------------------
# Contradiction — found by the Contradiction Detection pipeline
# ---------------------------------------------------------------------------

class Contradiction(Base):
    __tablename__ = "contradictions"

    id          = Column(String, primary_key=True, default=_uuid)
    project_id  = Column(String, nullable=False, index=True)
    topic       = Column(String, nullable=False)

    doc_id_1    = Column(String, ForeignKey("documents.doc_id"))
    chunk_id_1  = Column(String)
    text_1      = Column(Text)

    doc_id_2    = Column(String, ForeignKey("documents.doc_id"))
    chunk_id_2  = Column(String)
    text_2      = Column(Text)

    explanation = Column(Text)
    confidence  = Column(Float, default=0.0)
    created_at  = Column(DateTime, default=datetime.utcnow)


# ---------------------------------------------------------------------------
# KnowledgeGap — found by the Knowledge Gap pipeline
# ---------------------------------------------------------------------------

class KnowledgeGap(Base):
    __tablename__ = "knowledge_gaps"

    id          = Column(String, primary_key=True, default=_uuid)
    project_id  = Column(String, nullable=False, index=True)
    topic       = Column(String, nullable=False)
    description = Column(Text)
    created_at  = Column(DateTime, default=datetime.utcnow)


# ---------------------------------------------------------------------------
# Insight — found by the Proactive Insight pipeline
# ---------------------------------------------------------------------------

class Insight(Base):
    __tablename__ = "insights"

    id              = Column(String, primary_key=True, default=_uuid)
    project_id      = Column(String, nullable=False, index=True)

    # pattern | trend | anomaly
    insight_type    = Column(String)
    title           = Column(String)
    description     = Column(Text)

    # comma-separated doc_ids that support this insight
    supporting_docs = Column(Text)
    created_at      = Column(DateTime, default=datetime.utcnow)


# ---------------------------------------------------------------------------
# SmartQuestion — generated by Smart Question pipeline
# ---------------------------------------------------------------------------

class SmartQuestion(Base):
    __tablename__ = "smart_questions"

    id          = Column(String, primary_key=True, default=_uuid)
    project_id  = Column(String, nullable=False, index=True)
    question    = Column(Text, nullable=False)

    # comparison | factual | gap | trend
    category    = Column(String)
    created_at  = Column(DateTime, default=datetime.utcnow)


# ---------------------------------------------------------------------------
# SourceGuide — auto-generated summary + key topics per document
# ---------------------------------------------------------------------------

class SourceGuide(Base):
    __tablename__ = "source_guides"

    doc_id     = Column(String, ForeignKey("documents.doc_id"), primary_key=True)
    summary    = Column(Text)          # 2-3 sentence document summary
    key_topics = Column(Text)          # JSON array: ["topic1", "topic2", ...]
    created_at = Column(DateTime, default=datetime.utcnow)

    document = relationship("Document", back_populates="source_guide")


# ---------------------------------------------------------------------------
# AuditLog — every query + answer logged here
# ---------------------------------------------------------------------------

class AuditLog(Base):
    __tablename__ = "audit_logs"

    id            = Column(String, primary_key=True, default=_uuid)
    project_id    = Column(String, nullable=False, index=True)
    session_id    = Column(String)
    question      = Column(Text)
    answer        = Column(Text)

    # comma-separated chunk_ids used to answer
    chunks_used   = Column(Text)
    confidence    = Column(Float)
    model_version = Column(String)
    created_at    = Column(DateTime, default=datetime.utcnow)
